# Generated by Django 5.1.2 on 2025-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_rsvps_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default_event.jpg', upload_to='event_images/'),
        ),
    ]
